using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Arcane.ERP;
using Content.Shared._Arcane.ErpPanel;
using Content.Shared.IdentityManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Arcane.ErpPanel;

[GenerateTypedNameReferences]
public sealed partial class ErpPanelWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private static readonly Color ExplicitAccentColor = new(208, 100, 134);
    private static readonly Color FriendlyAccentColor = new(121, 203, 209);
    private static readonly Color DisabledControlColor = Color.FromHex("#FFFFFF66");
    private static readonly StyleBoxFlat CategoryStyle = CreateStyle(
        new Color(31, 37, 43),
        new Color(65, 75, 85),
        new Thickness(0, 0, 0, 1));
    private static readonly StyleBoxFlat CategoryHoverStyle = CreateStyle(
        new Color(42, 51, 59),
        FriendlyAccentColor,
        new Thickness(0, 0, 0, 1));
    private static readonly StyleBoxFlat ExplicitButtonStyle = CreateStyle(
        new Color(45, 36, 43),
        new Color(112, 70, 90),
        new Thickness(1));
    private static readonly StyleBoxFlat ExplicitButtonHoverStyle = CreateStyle(
        new Color(61, 43, 52),
        ExplicitAccentColor,
        new Thickness(1));
    private static readonly StyleBoxFlat FriendlyButtonStyle = CreateStyle(
        new Color(35, 47, 53),
        new Color(70, 106, 112),
        new Thickness(1));
    private static readonly StyleBoxFlat FriendlyButtonHoverStyle = CreateStyle(
        new Color(39, 58, 62),
        FriendlyAccentColor,
        new Thickness(1));
    private static readonly StyleBoxFlat DisabledButtonStyle = CreateStyle(
        new Color(28, 31, 35),
        new Color(54, 57, 61),
        new Thickness(1));
    private static readonly StyleBoxFlat ExplicitAccentStyle = CreateStyle(
        ExplicitAccentColor,
        ExplicitAccentColor,
        new Thickness());
    private static readonly StyleBoxFlat FriendlyAccentStyle = CreateStyle(
        FriendlyAccentColor,
        FriendlyAccentColor,
        new Thickness());
    private static readonly StyleBoxFlat ExplicitIconStyle = CreateStyle(
        new Color(30, 25, 29),
        new Color(112, 70, 90),
        new Thickness(1));
    private static readonly StyleBoxFlat FriendlyIconStyle = CreateStyle(
        new Color(24, 31, 35),
        new Color(70, 106, 112),
        new Thickness(1));
    private static readonly TimeSpan ReloadCooldown = TimeSpan.FromMilliseconds(100);
    private static readonly TimeSpan ArousalUpdateCooldown = TimeSpan.FromMilliseconds(50);
    private static readonly TimeSpan CooldownUpdateCooldown = TimeSpan.FromMilliseconds(100);

    private readonly SpriteSystem _sprite;
    private readonly ArousalSystem _arousal;
    private readonly TransformSystem _transform;
    private readonly HashSet<string> _openedCategories = new();
    private readonly Dictionary<string, Collapsible> _categoryControls = new();
    private readonly Dictionary<string, Button> _interactionButtons = new();
    private readonly Dictionary<string, StyleBoxFlat> _interactionButtonStyles = new();
    private readonly Dictionary<string, TimeSpan> _cooldownEnds = new();
    private readonly Dictionary<string, string> _interactionNames = new();
    private readonly Dictionary<string, string> _categoryNames = new();

    private TimeSpan _lastInteractionUpdate = TimeSpan.Zero;
    private TimeSpan _lastArousalUpdate = TimeSpan.Zero;
    private TimeSpan _lastCooldownUpdate = TimeSpan.Zero;
    private EntityUid? _currentUser;
    private EntityUid? _currentTarget;
    private List<string> _currentInteractions = new();
    private bool _hasInitializedCategories;

    public Action<string, float, float>? OnSendEmote;

    public ErpPanelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();
        _arousal = _entManager.System<ArousalSystem>();
        _transform = _entManager.System<TransformSystem>();

        SearchInput.OnTextChanged += _ =>
        {
            ClearSearchButton.Disabled = string.IsNullOrWhiteSpace(SearchInput.Text);
            ReloadInteractionsIfNeeded(true);
        };
        ClearSearchButton.OnPressed += _ => SearchInput.Text = string.Empty;
        ClearSearchButton.Disabled = true;

        CustomArousalToggle.OnToggled += args => SetModifierEnabled(
            ArousalSlider,
            ArousalLabel,
            args.Pressed,
            ExplicitAccentColor);
        CustomMoaningToggle.OnToggled += args => SetModifierEnabled(
            MoaningSlider,
            MoaningLabel,
            args.Pressed,
            FriendlyAccentColor);

        ArousalSlider.OnValueChanged += _ => UpdateMultiplierLabels();
        MoaningSlider.OnValueChanged += _ => UpdateMultiplierLabels();

        ExpandAllButton.OnPressed += _ => SetAllCategoriesExpanded(true);
        CollapseAllButton.OnPressed += _ => SetAllCategoriesExpanded(false);
        ModifiersVisibilityButton.OnPressed += _ => SetModifiersVisible(!ModifiersContent.Visible);

        SetModifierEnabled(ArousalSlider, ArousalLabel, false, ExplicitAccentColor);
        SetModifierEnabled(MoaningSlider, MoaningLabel, false, FriendlyAccentColor);
        UpdateMultiplierLabels();
        ArousalValueLabel.Text = FormatPercent(0);
    }

    public void SetTarget(NetEntity user, NetEntity target)
    {
        _currentUser = _entManager.GetEntity(user);
        _currentTarget = _entManager.GetEntity(target);
        _currentInteractions.Clear();
        _openedCategories.Clear();
        _hasInitializedCategories = false;

        if (_currentUser == null || _currentTarget == null)
            return;

        var targetName = Identity.Name(_currentTarget.Value, _entManager, _currentUser.Value);
        HeaderLabel.Text = targetName;
        HeaderLabel.ToolTip = Loc.GetString("erp-panel-header", ("target", targetName));

        ReloadInteractionsIfNeeded(true);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!IsOpen)
            return;

        UpdateCooldowns();
        UpdateArousal();
        ReloadInteractionsIfNeeded();
    }

    private void UpdateMultiplierLabels()
    {
        ArousalLabel.Text = FormatPercent(ArousalSlider.Value);
        MoaningLabel.Text = FormatPercent(MoaningSlider.Value);
    }

    private static void SetModifierEnabled(Slider slider, Label valueLabel, bool enabled, Color activeColor)
    {
        slider.Disabled = !enabled;
        slider.Modulate = enabled ? Color.White : DisabledControlColor;
        valueLabel.Modulate = enabled ? activeColor : DisabledControlColor;
    }

    private void UpdateCooldowns()
    {
        var now = _timing.CurTime;
        if (_lastCooldownUpdate + CooldownUpdateCooldown > now)
            return;

        _lastCooldownUpdate = now;

        foreach (var interactionId in _cooldownEnds.Keys.ToList())
        {
            var cooldownEnd = _cooldownEnds[interactionId];
            if (cooldownEnd <= now)
            {
                _cooldownEnds.Remove(interactionId);

                if (_interactionButtons.TryGetValue(interactionId, out var readyButton))
                {
                    readyButton.Disabled = false;
                    readyButton.StyleBoxOverride = _interactionButtonStyles.GetValueOrDefault(interactionId);
                    readyButton.ToolTip = _interactionNames.GetValueOrDefault(interactionId);
                }

                continue;
            }

            if (!_interactionButtons.TryGetValue(interactionId, out var button))
                continue;

            button.Disabled = true;
            button.StyleBoxOverride = DisabledButtonStyle;
            var seconds = Math.Max(1, (int) Math.Ceiling((cooldownEnd - now).TotalSeconds));
            button.ToolTip = Loc.GetString("erp-panel-interaction-cooldown-tooltip", ("seconds", seconds));
        }
    }

    private void UpdateArousal()
    {
        if (_lastArousalUpdate + ArousalUpdateCooldown > _timing.CurTime)
            return;

        _lastArousalUpdate = _timing.CurTime;

        if (!_entManager.TryGetComponent<ArousalComponent>(_currentUser, out var userArousal) ||
            userArousal.MaxArousal <= 0)
        {
            SetArousalDisplay(0);
            return;
        }

        var percent = _arousal.GetArousal(userArousal) / userArousal.MaxArousal;
        SetArousalDisplay(Math.Clamp(percent, 0f, 1f));
    }

    private void SetArousalDisplay(float targetValue)
    {
        var difference = targetValue - ArousalProgressBar.Value;
        ArousalProgressBar.Value += 0.1f * difference;
        ArousalValueLabel.Text = FormatPercent(targetValue * 100);
    }

    private void ReloadInteractionsIfNeeded(bool force = false)
    {
        if (!_currentUser.HasValue || !_currentTarget.HasValue)
            return;

        var now = _timing.CurTime;
        if (!force && now < _lastInteractionUpdate + ReloadCooldown)
            return;

        _lastInteractionUpdate = now;

        var interactions = GetAvailableInteractions(_currentUser.Value, _currentTarget.Value);
        var interactionIds = interactions
            .Select(interaction => interaction.ID)
            .ToList();

        interactionIds.Sort();

        if (!force && _currentInteractions.SequenceEqual(interactionIds))
            return;

        _currentInteractions = interactionIds;
        ReloadInteractions(interactions);
    }

    private List<PanelInteractionPrototype> GetAvailableInteractions(EntityUid user, EntityUid target)
    {
        var searchText = SearchInput.Text.Trim();
        var interactions = new List<PanelInteractionPrototype>();

        foreach (var interaction in _prototypeManager.EnumeratePrototypes<PanelInteractionPrototype>())
        {
            if (!IsInteractionAvailable(user, target, interaction))
                continue;

            if (!InteractionMatchesSearch(interaction, searchText))
                continue;

            interactions.Add(interaction);
        }

        return interactions;
    }

    private bool IsInteractionAvailable(EntityUid user, EntityUid target, PanelInteractionPrototype interaction)
    {
        if (interaction.Messages.Count == 0)
            return false;

        if (user == target && interaction.SelfMessages.Count == 0)
            return false;

        return CheckRequirements(user, target, interaction);
    }

    private void ReloadInteractions(List<PanelInteractionPrototype> interactions)
    {
        ButtonsContainer.DisposeAllChildren();
        _categoryControls.Clear();
        _interactionButtons.Clear();
        _interactionButtonStyles.Clear();

        var interactionsByCategory = interactions
            .GroupBy(interaction => interaction.Category.Id)
            .ToDictionary(
                group => group.Key,
                group => group.OrderBy(GetInteractionName).ToList());

        // Автооткрытие первой категории
        var openFirstCategory = !_hasInitializedCategories && string.IsNullOrWhiteSpace(SearchInput.Text);

        foreach (var category in _prototypeManager.EnumeratePrototypes<PanelInteractionCategoryPrototype>())
        {
            if (!interactionsByCategory.TryGetValue(category.ID, out var categoryInteractions))
                continue;

            var categoryControl = PrepareInteractionCategory(category, categoryInteractions.Count);
            var categoryGrid = new GridContainer
            {
                Columns = 2,
                HorizontalExpand = true,
                HSeparationOverride = 6,
                VSeparationOverride = 6,
                Margin = new Thickness(4, 6, 4, 2),
            };

            foreach (var interaction in categoryInteractions)
                categoryGrid.AddChild(PrepareInteractionButton(interaction));

            ButtonsContainer.AddChild(categoryControl);
            categoryControl.Body?.AddChild(categoryGrid);
            _categoryControls[category.ID] = categoryControl;

            if (openFirstCategory)
            {
                categoryControl.BodyVisible = true;
                _openedCategories.Add(category.ID);
                openFirstCategory = false;
            }
        }

        _hasInitializedCategories = true;
        UpdateCatalogSummary(interactions.Count);
        UpdateCooldownsImmediately();
    }

    private Collapsible PrepareInteractionCategory(PanelInteractionCategoryPrototype categoryPrototype, int count)
    {
        var title = Loc.GetString(
            "erp-panel-category-heading",
            ("category", GetCategoryName(categoryPrototype)),
            ("count", count));
        var heading = new CollapsibleHeading(title)
        {
            ChevronMargin = new Thickness(8, 0),
            HorizontalExpand = true,
            MinHeight = 34,
            StyleBoxOverride = CategoryStyle,
        };
        heading.Label.StyleClasses.Add(StyleBase.StyleClassLabelHeading);

        heading.Label.FontColorOverride = new Color(235, 240, 244);
        heading.Label.HorizontalExpand = true;
        heading.Label.ClipText = true;
        heading.OnMouseEntered += _ => heading.StyleBoxOverride = CategoryHoverStyle;
        heading.OnMouseExited += _ => heading.StyleBoxOverride = CategoryStyle;

        var category = new Collapsible(heading, new CollapsibleBody())
        {
            HorizontalExpand = true,
        };

        heading.OnToggled += args =>
        {
            if (args.Pressed)
                _openedCategories.Add(categoryPrototype.ID);
            else
                _openedCategories.Remove(categoryPrototype.ID);
        };

        category.BodyVisible = !string.IsNullOrWhiteSpace(SearchInput.Text) ||
                               _openedCategories.Contains(categoryPrototype.ID);

        return category;
    }

    private void SetModifiersVisible(bool visible)
    {
        ModifiersContent.Visible = visible;
        ModifiersVisibilityButton.Text = Loc.GetString(
            visible ? "erp-panel-hide-modifiers" : "erp-panel-show-modifiers");
    }

    private Button PrepareInteractionButton(PanelInteractionPrototype interaction)
    {
        var interactionName = GetInteractionName(interaction);
        var isExplicit = IsErpInteraction(interaction);
        var accentColor = isExplicit ? ExplicitAccentColor : FriendlyAccentColor;
        var normalStyle = isExplicit ? ExplicitButtonStyle : FriendlyButtonStyle;
        var hoverStyle = isExplicit ? ExplicitButtonHoverStyle : FriendlyButtonHoverStyle;
        var button = new Button
        {
            HorizontalExpand = true,
            MinWidth = 250,
            MinHeight = 56,
            ToolTip = interactionName,
            StyleClasses = { StyleBase.ButtonSquare },
            StyleBoxOverride = normalStyle,
        };

        var content = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(7, 5),
            SeparationOverride = 8,
            MouseFilter = MouseFilterMode.Ignore,
        };
        var accent = new PanelContainer
        {
            MinWidth = 3,
            VerticalExpand = true,
            PanelOverride = isExplicit ? ExplicitAccentStyle : FriendlyAccentStyle,
            MouseFilter = MouseFilterMode.Ignore,
        };
        var iconFrame = new PanelContainer
        {
            MinWidth = 40,
            MinHeight = 40,
            PanelOverride = isExplicit ? ExplicitIconStyle : FriendlyIconStyle,
            MouseFilter = MouseFilterMode.Ignore,
        };
        var icon = new TextureRect
        {
            Texture = _sprite.Frame0(interaction.Icon),
            MinWidth = 32,
            MinHeight = 32,
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
        };
        var label = new Label
        {
            Text = interactionName,
            ClipText = true,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            ToolTip = interactionName,
            MouseFilter = MouseFilterMode.Ignore,
        };
        var arrow = new TextureRect
        {
            StyleClasses = { OptionButton.StyleClassOptionTriangle },
            Modulate = accentColor,
            MinWidth = 12,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
        };

        button.OnMouseEntered += _ =>
        {
            if (button.Disabled)
                return;

            button.StyleBoxOverride = hoverStyle;
            arrow.Modulate = Color.White;
        };
        button.OnMouseExited += _ =>
        {
            if (button.Disabled)
                return;

            button.StyleBoxOverride = normalStyle;
            arrow.Modulate = accentColor;
        };

        button.OnPressed += _ =>
        {
            OnSendEmote?.Invoke(
                interaction.ID,
                CustomArousalToggle.Pressed ? ArousalSlider.Value : 100f,
                CustomMoaningToggle.Pressed ? MoaningSlider.Value : 100f);

            if (interaction.Cooldown <= TimeSpan.Zero)
                return;

            _cooldownEnds[interaction.ID] = _timing.CurTime + interaction.Cooldown;
            UpdateCooldownsImmediately();
        };

        iconFrame.AddChild(icon);
        content.AddChild(accent);
        content.AddChild(iconFrame);
        content.AddChild(label);
        content.AddChild(arrow);
        button.AddChild(content);
        _interactionButtons[interaction.ID] = button;
        _interactionButtonStyles[interaction.ID] = normalStyle;

        return button;
    }

    private void UpdateCatalogSummary(int interactionCount)
    {
        ResultsLabel.Text = Loc.GetString("erp-panel-results", ("count", interactionCount));

        var hasInteractions = interactionCount > 0;
        InteractionScroll.Visible = hasInteractions;
        EmptyStateContainer.Visible = !hasInteractions;
        EmptyStateLabel.Text = Loc.GetString(
            string.IsNullOrWhiteSpace(SearchInput.Text)
                ? "erp-panel-empty-available"
                : "erp-panel-empty-search");

        ExpandAllButton.Disabled = _categoryControls.Count == 0;
        CollapseAllButton.Disabled = _categoryControls.Count == 0;
    }

    private void SetAllCategoriesExpanded(bool expanded)
    {
        foreach (var (categoryId, category) in _categoryControls)
        {
            category.BodyVisible = expanded;

            if (expanded)
                _openedCategories.Add(categoryId);
            else
                _openedCategories.Remove(categoryId);
        }
    }

    private void UpdateCooldownsImmediately()
    {
        // Фикс спама
        _lastCooldownUpdate = _timing.CurTime - CooldownUpdateCooldown;
        UpdateCooldowns();
    }

    private bool InteractionMatchesSearch(PanelInteractionPrototype interaction, string searchText)
    {
        if (string.IsNullOrEmpty(searchText))
            return true;

        if (GetInteractionName(interaction).Contains(searchText, StringComparison.CurrentCultureIgnoreCase))
            return true;

        var category = _prototypeManager.Index<PanelInteractionCategoryPrototype>(interaction.Category.Id);
        return GetCategoryName(category).Contains(searchText, StringComparison.CurrentCultureIgnoreCase);
    }

    private string GetInteractionName(PanelInteractionPrototype interaction)
    {
        if (_interactionNames.TryGetValue(interaction.ID, out var name))
            return name;

        name = Loc.GetString($"erp-panel-interaction-{ToKebabCase(interaction.ID)}-name");
        _interactionNames[interaction.ID] = name;
        return name;
    }

    private string GetCategoryName(PanelInteractionCategoryPrototype category)
    {
        if (_categoryNames.TryGetValue(category.ID, out var name))
            return name;

        name = Loc.GetString($"erp-panel-category-{ToKebabCase(category.ID)}-name");
        _categoryNames[category.ID] = name;
        return name;
    }

    private static string FormatPercent(double value)
    {
        return $"{(int) Math.Round(value)}%";
    }

    private static StyleBoxFlat CreateStyle(Color backgroundColor, Color borderColor, Thickness borderThickness)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = backgroundColor,
            BorderColor = borderColor,
            BorderThickness = borderThickness,
        };
    }

    private static string ToKebabCase(string value)
    {
        var builder = new System.Text.StringBuilder(value.Length * 2);

        for (var i = 0; i < value.Length; i++)
        {
            var character = value[i];

            if (char.IsUpper(character))
            {
                if (i > 0)
                    builder.Append('-');

                builder.Append(char.ToLowerInvariant(character));
                continue;
            }

            builder.Append(character);
        }

        return builder.ToString();
    }

    private bool CheckRequirements(EntityUid user, EntityUid target, PanelInteractionPrototype interaction)
    {
        if (IsErpInteraction(interaction) && !CanUseErp(user, target))
            return false;

        if (!_transform.InRange(user, target, interaction.Range))
            return false;

        if (interaction.UserRequirements != null)
        {
            foreach (var requirement in interaction.UserRequirements)
            {
                if (!requirement.IsAvailable(user, _entManager))
                    return false;
            }
        }

        if (interaction.TargetRequirements != null)
        {
            foreach (var requirement in interaction.TargetRequirements)
            {
                if (!requirement.IsAvailable(target, _entManager))
                    return false;
            }
        }

        return true;
    }

    private static bool IsErpInteraction(PanelInteractionPrototype interaction)
    {
        return interaction.Tags.Contains(ErpPanelConstants.ErpInteractionTag);
    }

    private bool CanUseErp(EntityUid user, EntityUid target)
    {
        if (_entManager.TryGetComponent<ErpStatusComponent>(user, out var userStatus) &&
            userStatus.Preference == ErpPreference.No)
            return false;

        if (user != target &&
            _entManager.TryGetComponent<ErpStatusComponent>(target, out var targetStatus) &&
            targetStatus.Preference == ErpPreference.No)
            return false;

        return true;
    }
}
